spring.output.ansi.enabled: always
server:
  port: 8089



#database 연동 설정  (db_codingrecipe스키마 이름)
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   각자 PC에 만들어놓은 Database이름을 써야 된다.
    url: jdbc:mysql://localhost:3306/capoeiraweb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#   mysql에 생성한 사용자 계정 정보를 써야 된다
    username: caUser
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update #create로 하면 새로운 테이블을 만든다. update
